const dataCars = [
  {
    _id: 1,
    name: 'Jeep Wrangler',
    images: [
      '/images/j1.png',
      '/images/j2.png',
      '/images/j3.png',
      'jeep4.jpg',
      'jeep5.jpg',
      'jeep6.jpg',
    ],
    description: 'A rugged and versatile off-road SUV.',
    review: '4.5',
    available: true,
    mpg: '18',
    doors: '2',
    gas: 'Petrol',
    seats: '4',
    transmission: 'Manual',
    pricePerDay: '96',
    owner: {
      name: 'John Doe',
      image: 'owner1.jpg',
    },
    location: {
      latitude: 40.7128,
      longitude: -74.006,
    },
    category: 'SUV',
  },
  {
    _id: 2,
    name: 'Jeep Grand Cherokee',
    images: [
      '/images/j3.png',
      '/images/j2.png',
      'jeepgc3.jpg',
      'jeepgc4.jpg',
      'jeepgc5.jpg',
      'jeepgc6.jpg',
    ],
    description: 'A spacious and comfortable SUV for all terrains.',
    review: '4.2',
    available: true,
    mpg: '20',
    doors: '4',
    gas: 'Petrol',
    seats: '5',
    transmission: 'Automatic',
    pricePerDay: '106',
    owner: {
      name: 'Jane Smith',
      image: 'owner2.jpg',
    },
    location: {
      latitude: 34.0522,
      longitude: -118.2437,
    },
    category: 'SUV',
  },
  {
    _id: 3,
    name: 'Tesla Model 3',
    images: [
      '/images/j2.png',
      '/images/j1.png',
      'tesla3.jpg',
      'tesla4.jpg',
      'tesla5.jpg',
      'tesla6.jpg',
    ],
    description: 'An electric sedan with impressive performance and range.',
    review: '4.8',
    available: true,
    mpg: 'Electric',
    doors: '4',
    gas: 'Electric',
    seats: '5',
    transmission: 'Automatic',
    pricePerDay: '86',
    owner: {
      name: 'Michael Johnson',
      image: 'owner3.jpg',
    },
    location: {
      latitude: 51.5074,
      longitude: -0.1278,
    },
    category: 'jeep',
  },
  {
    _id: 4,
    name: 'Tesla Model 3',
    images: [
      '/images/j1.png',
      '/images/j2.png',
      'tesla3.jpg',
      'tesla4.jpg',
      'tesla5.jpg',
      'tesla6.jpg',
    ],
    description: 'An electric sedan with impressive performance and range.',
    review: '4.8',
    available: true,
    mpg: 'Electric',
    doors: '4',
    gas: 'Electric',
    seats: '5',
    transmission: 'Automatic',
    pricePerDay: '56',
    owner: {
      name: 'Michael Johnson',
      image: 'owner3.jpg',
    },
    location: {
      latitude: 51.5074,
      longitude: -0.1278,
    },
    category: 'jeep',
  },
]

export default dataCars
